from pydantic import BaseModel, Field
from typing import List, Optional, Any, Union

class QuestionRequest(BaseModel):
    question: str = Field(..., description="The natural language question to ask about support tickets.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The natural language answer generated by the system.")

class AnomalyResponse(BaseModel):
    ticket_id: str = Field(..., description="The unique ticket ID of the anomaly.")
    reason: str = Field(..., description="The reason why this ticket was flagged as an anomaly.")

class SummaryResponse(BaseModel):
    total_tickets: int = Field(..., description="Total number of tickets in the dataset.")
    open_tickets: int = Field(..., description="Number of tickets currently open.")
    resolved_tickets: int = Field(..., description="Number of tickets that have been resolved.")
    average_customer_rating: Optional[float] = Field(None, description="Average customer rating for resolved tickets.")

class FilterCondition(BaseModel):
    column: str = Field(..., description="Column to apply the filter on (e.g. status, priority, category, agent_id, customer_rating, resolution_time_hrs, response_time_hrs, created_at)")
    operator: str = Field(..., description="The comparison operator: ==, !=, >, <, >=, <=, contains, is_null, not_null")
    value: Any = Field(None, description="Value to compare against. Can be null for is_null and not_null operators.")

class StructuredQuery(BaseModel):
    metric: str = Field(..., description="The metric or aggregation type: count, mean, sum, min, max, or list (if user is asking to list tickets).")
    target_column: Optional[str] = Field(None, description="The column to aggregate (e.g. customer_rating, resolution_time_hrs, response_time_hrs). Required if metric is mean, sum, min, max.")
    filters: Optional[List[FilterCondition]] = Field(default=[], description="List of filter conditions to apply to the dataset.")
    group_by: Optional[str] = Field(None, description="Column to group by, e.g. agent_id, category, priority, status.")
    sort: Optional[str] = Field(None, description="Sort order: ascending, descending. Usually required if asking for 'highest', 'lowest', 'most', 'least'.")
    limit: Optional[int] = Field(None, description="Max number of records to return. E.g. limit to 1 if asking for 'lowest' or 'highest'.")
